#!/bin/bash
re='^-[0-9]+$'
re2='^[0-9]+$'
m=$(( $1 % 5 ))
if ! [[ $1 =~ $re2 ]] && ! [[ $1 =~ $re ]] ; then
   echo "error: Not a number" >&2; exit 1
fi
	#statements
	if [[ $1 -gt 0 ]]; then
		echo "Yo, this number is positive"
	elif [[ $1 -lt 0 ]]; then
		echo "Yo, this number is negative"
	fi

		if [[ $m -eq 0 ]]; then
			echo "Yo, this number is 5 blah blah"
		fi